import { useEffect, useState, type ReactNode } from 'react';
import { Alert, Avatar, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Drawer, FormControl, Grid, IconButton, InputLabel, MenuItem, Paper, Select, Stack, Switch, Table, TableBody, TableCell, TableHead, TableRow, TextField, Toolbar, Typography } from '@mui/material';
import { AdminPanelSettings, AutoAwesome, Dashboard, History, IntegrationInstructions, Logout, Menu, People, RocketLaunch, Settings, Add, Archive, PersonOff } from '@mui/icons-material';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { adminApi, type AdminActivity, type AdminProject, type AdminUser } from '../services/adminService';

const ink = '#142b46';
const muted = '#718096';
const accent = '#278f87';
const surface = { border: '1px solid #e3e9ed', borderRadius: '14px', boxShadow: '0 8px 28px rgba(20,43,70,.045)' };
const roles = ['admin', 'project_manager', 'developer', 'team_member'];
const nav = [['Dashboard', '/admin-dashboard', Dashboard], ['Users', '/admin-dashboard/users', People], ['Projects', '/admin-dashboard/projects', RocketLaunch], ['Integrations', '/admin-dashboard/integrations', IntegrationInstructions], ['AI & Workflow', '/admin-dashboard/ai-settings', AutoAwesome], ['Activity Logs', '/admin-dashboard/activity', History], ['Settings', '/admin-dashboard/settings', Settings]] as const;

function EmptyState({ label }: { label: string }) { return <Box sx={{ p: 5, textAlign: 'center' }}><Typography sx={{ color: muted }}>{label}</Typography></Box>; }
function Header({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2} sx={{ mb: 3 }}><Box><Typography sx={{ color: accent, fontSize: '.68rem', fontWeight: 850, textTransform: 'uppercase', letterSpacing: '.14em' }}>Admin console</Typography><Typography component="h1" sx={{ mt: .5, color: ink, fontSize: { xs: '1.65rem', sm: '2rem' }, fontWeight: 850 }}>{title}</Typography><Typography sx={{ mt: .5, color: muted, fontSize: '.88rem' }}>{detail}</Typography></Box>{action}</Stack>; }
function Status({ value }: { value: string }) { return <Chip size="small" label={value} sx={{ color: value === 'Active' || value === 'Success' ? accent : '#d99045', bgcolor: value === 'Active' || value === 'Success' ? '#278f8718' : '#d9904518', fontWeight: 750 }} />; }

function AdminSidebar({ open, onClose }: { open: boolean; onClose: () => void }) {
  const navigate = useNavigate(); const location = useLocation(); const { signOut, user } = useAuth();
  const content = <Box sx={{ width: 268, height: '100%', bgcolor: '#10243e', display: 'flex', flexDirection: 'column' }}><Box sx={{ p: 2.8 }}><Stack direction="row" spacing={1.2} alignItems="center"><Box sx={{ width: 36, height: 36, display: 'grid', placeItems: 'center', borderRadius: '11px', bgcolor: '#76d0c5', color: '#10243e' }}><AdminPanelSettings fontSize="small" /></Box><Box><Typography sx={{ color: '#fff', fontWeight: 850 }}>AI DevFlow</Typography><Typography sx={{ color: '#76d0c5', fontWeight: 750, fontSize: '.75rem' }}>ADMIN CONSOLE</Typography></Box></Stack></Box><Divider sx={{ borderColor: 'rgba(255,255,255,.1)' }} /><Stack component="nav" spacing={.45} sx={{ p: 1.5, flex: 1 }}>{nav.map(([label, path, Icon]) => { const active = location.pathname === path; return <Button key={path} onClick={() => { navigate(path); onClose(); }} startIcon={<Icon sx={{ fontSize: 18 }} />} sx={{ justifyContent: 'flex-start', px: 1.4, py: 1.05, color: active ? '#10243e' : '#aebed0', bgcolor: active ? '#76d0c5' : 'transparent', '&:hover': { bgcolor: active ? '#76d0c5' : 'rgba(255,255,255,.08)' }, textTransform: 'none', fontWeight: active ? 800 : 600 }}>{label}</Button>; })}</Stack><Box sx={{ p: 1.5, borderTop: '1px solid rgba(255,255,255,.1)' }}><Stack direction="row" spacing={1.2} alignItems="center"><Avatar sx={{ width: 32, height: 32, bgcolor: '#d99045' }}>{user?.full_name?.slice(0, 1) ?? 'A'}</Avatar><Box sx={{ flex: 1 }}><Typography sx={{ color: '#fff', fontSize: '.8rem', fontWeight: 750 }}>{user?.full_name || user?.email || 'Administrator'}</Typography><Typography sx={{ color: '#91a4ba', fontSize: '.68rem' }}>Administrator</Typography></Box><IconButton size="small" onClick={() => { signOut(); navigate('/login'); }} sx={{ color: '#91a4ba' }} aria-label="Logout"><Logout fontSize="small" /></IconButton></Stack></Box></Box>;
  return <><Drawer variant="permanent" sx={{ display: { xs: 'none', md: 'block' }, '& .MuiDrawer-paper': { width: 268, border: 0 } }}>{content}</Drawer><Drawer variant="temporary" open={open} onClose={onClose} sx={{ display: { xs: 'block', md: 'none' }, '& .MuiDrawer-paper': { width: 268, border: 0 } }}>{content}</Drawer></>;
}

function DashboardPage({ revision }: { revision: number }) {
  const [data, setData] = useState<{ metrics: Record<string, number>; activity: AdminActivity[] } | null>(null); const [error, setError] = useState('');
  useEffect(() => { adminApi.dashboard().then(setData).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load dashboard.')); const timer = window.setInterval(() => adminApi.dashboard().then(setData).catch(() => undefined), 15000); return () => window.clearInterval(timer); }, [revision]);
  if (error) return <Alert severity="error">{error}</Alert>;
  const metrics = data?.metrics;
  const cards = [{ label: 'Total users', key: 'users', Icon: People }, { label: 'Active projects', key: 'projects', Icon: RocketLaunch }, { label: 'Open tasks', key: 'tasks', Icon: Dashboard }, { label: 'Workflow risks', key: 'risks', Icon: AutoAwesome }, { label: 'Connected repositories', key: 'repositories', Icon: IntegrationInstructions }];
  return <><Header title="Workspace overview" detail="Live administration metrics from the database." /><Grid container spacing={2}>{cards.map(({ label, key, Icon }) => <Grid item xs={6} md={4} lg={2.4} key={key}><Paper sx={{ ...surface, p: 2.2 }}><Icon sx={{ color: accent }} /><Typography sx={{ color: muted, mt: 1.5, fontSize: '.77rem' }}>{label}</Typography><Typography sx={{ color: ink, mt: .3, fontWeight: 850, fontSize: '1.7rem' }}>{metrics?.[key] ?? 0}</Typography></Paper></Grid>)}</Grid><Paper sx={{ ...surface, mt: 2.5, p: 2.5 }}><Typography sx={{ color: ink, fontWeight: 800 }}>Recent activity</Typography>{data?.activity.length ? <Stack divider={<Divider />} sx={{ mt: 1 }}>{data.activity.map((item) => <Stack key={item.id} direction="row" justifyContent="space-between" sx={{ py: 1.3 }}><Box><Typography sx={{ color: ink, fontSize: '.82rem', fontWeight: 700 }}>{item.action}</Typography><Typography sx={{ color: muted, fontSize: '.72rem' }}>{item.module}</Typography></Box><Typography sx={{ color: muted, fontSize: '.72rem' }}>{new Date(item.created_at).toLocaleString()}</Typography></Stack>)}</Stack> : <EmptyState label="No activity found" />}</Paper></>;
}

function UsersPage({ onChange }: { onChange: () => void }) {
  const [items, setItems] = useState<AdminUser[]>([]); const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [form, setForm] = useState({ full_name: '', email: '', password: '', role: 'team_member' });
  const load = () => adminApi.users().then(setItems).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load users.'));
  useEffect(() => { load(); }, []);
  const filtered = items.filter((item) => `${item.full_name} ${item.email}`.toLowerCase().includes(query.toLowerCase()));
  async function create() { try { await adminApi.createUser(form); setOpen(false); setForm({ full_name: '', email: '', password: '', role: 'team_member' }); await load(); onChange(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create user.'); } }
  return <><Header title="Users" detail="Manage real accounts and access." action={<Button variant="contained" startIcon={<Add />} onClick={() => setOpen(true)}>Add user</Button>} />{error && <Alert sx={{ mb: 2 }} severity="error">{error}</Alert>}<TextField size="small" placeholder="Search users" value={query} onChange={(event) => setQuery(event.target.value)} sx={{ mb: 2, width: { xs: '100%', sm: 360 } }} /><Paper sx={{ ...surface, overflow: 'auto' }}><Table><TableHead><TableRow>{['Name', 'Email', 'Role', 'Status', 'Created', 'Actions'].map((head) => <TableCell key={head}>{head}</TableCell>)}</TableRow></TableHead><TableBody>{filtered.length ? filtered.map((item) => <TableRow key={item.id}><TableCell>{item.full_name || 'Unnamed user'}</TableCell><TableCell>{item.email}</TableCell><TableCell>{item.role}</TableCell><TableCell><Status value={item.is_active ? 'Active' : 'Inactive'} /></TableCell><TableCell>{new Date(item.created_at).toLocaleDateString()}</TableCell><TableCell><IconButton aria-label="Deactivate user" onClick={() => adminApi.deactivateUser(item.id).then(() => { load(); onChange(); })}><PersonOff /></IconButton></TableCell></TableRow>) : <TableRow><TableCell colSpan={6}><EmptyState label="No users found" /></TableCell></TableRow>}</TableBody></Table></Paper><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Add user</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Full name" value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} /><TextField label="Email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><TextField label="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><FormControl><InputLabel>Role</InputLabel><Select label="Role" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}>{roles.map((role) => <MenuItem key={role} value={role}>{role}</MenuItem>)}</Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" onClick={create}>Create user</Button></DialogActions></Dialog></>;
}

function ProjectsPage({ onChange }: { onChange: () => void }) {
  const [items, setItems] = useState<AdminProject[]>([]); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', description: '', manager_id: null as number | null, status: 'Active', start_date: null as string | null, end_date: null as string | null }); const [error, setError] = useState('');
  const load = () => adminApi.projects().then(setItems).catch((cause) => setError(cause instanceof Error ? cause.message : 'Unable to load projects.'));
  useEffect(() => { load(); }, []);
  async function create() { try { await adminApi.createProject(form); setOpen(false); setForm({ name: '', description: '', manager_id: null, status: 'Active', start_date: null, end_date: null }); await load(); onChange(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create project.'); } }
  return <><Header title="Projects" detail="Manage database-backed delivery workspaces." action={<Button variant="contained" startIcon={<Add />} onClick={() => setOpen(true)}>Create project</Button>} />{error && <Alert sx={{ mb: 2 }} severity="error">{error}</Alert>}<Paper sx={{ ...surface, overflow: 'auto' }}><Table><TableHead><TableRow>{['Project', 'Manager', 'Members', 'Status', 'Created', 'Actions'].map((head) => <TableCell key={head}>{head}</TableCell>)}</TableRow></TableHead><TableBody>{items.filter((item) => !item.archived).length ? items.filter((item) => !item.archived).map((item) => <TableRow key={item.id}><TableCell><Typography sx={{ fontWeight: 750 }}>{item.name}</Typography><Typography sx={{ color: muted, fontSize: '.75rem' }}>{item.description}</Typography></TableCell><TableCell>{item.manager_name || 'Unassigned'}</TableCell><TableCell>{item.members}</TableCell><TableCell><Status value={item.status} /></TableCell><TableCell>{new Date(item.created_at).toLocaleDateString()}</TableCell><TableCell><IconButton aria-label="Archive project" onClick={() => adminApi.archiveProject(item.id).then(() => { load(); onChange(); })}><Archive /></IconButton></TableCell></TableRow>) : <TableRow><TableCell colSpan={6}><EmptyState label="No projects found" /></TableCell></TableRow>}</TableBody></Table></Paper><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Create project</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Project name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><TextField label="Description" multiline rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><FormControl><InputLabel>Status</InputLabel><Select label="Status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{['Active', 'At Risk', 'Completed', 'On Hold'].map((status) => <MenuItem key={status} value={status}>{status}</MenuItem>)}</Select></FormControl><TextField label="Start date" type="date" InputLabelProps={{ shrink: true }} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /><TextField label="End date" type="date" InputLabelProps={{ shrink: true }} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" onClick={create}>Create project</Button></DialogActions></Dialog></>;
}

function ActivityPage() { const [items, setItems] = useState<AdminActivity[]>([]); useEffect(() => { adminApi.activity().then(setItems).catch(() => setItems([])); }, []); return <><Header title="Activity logs" detail="Successful administrative operations recorded by the backend." /><Paper sx={{ ...surface, overflow: 'auto' }}><Table><TableHead><TableRow>{['Timestamp', 'User', 'Action', 'Module', 'Status'].map((head) => <TableCell key={head}>{head}</TableCell>)}</TableRow></TableHead><TableBody>{items.length ? items.map((item) => <TableRow key={item.id}><TableCell>{new Date(item.created_at).toLocaleString()}</TableCell><TableCell>{item.user || 'Unknown user'}</TableCell><TableCell>{item.action}</TableCell><TableCell>{item.module}</TableCell><TableCell><Status value={item.status} /></TableCell></TableRow>) : <TableRow><TableCell colSpan={5}><EmptyState label="No activity found" /></TableCell></TableRow>}</TableBody></Table></Paper></>; }
function AISettingsPage() { const [settings, setSettings] = useState<Record<string, boolean>>({}); useEffect(() => { adminApi.settings().then(setSettings).catch(() => undefined); }, []); const keys = [['workflow_risk_detection', 'Workflow risk detection'], ['task_delay_detection', 'Task delay detection'], ['pull_request_monitoring', 'Pull request review monitoring'], ['ai_recommendations', 'AI recommendations']]; return <><Header title="AI & workflow" detail="Persisted switches for future analysis of real development activity." /><Paper sx={{ ...surface, p: 2.5, maxWidth: 760 }}>{keys.map(([key, label]) => <Stack key={key} direction="row" justifyContent="space-between" alignItems="center" sx={{ py: 1.8, borderBottom: '1px solid #edf1f3' }}><Typography sx={{ color: ink, fontWeight: 700 }}>{label}</Typography><Switch checked={Boolean(settings[key])} onChange={(event) => { const next = { ...settings, [key]: event.target.checked }; setSettings(next); adminApi.updateSettings(next); }} /></Stack>)}</Paper></>; }
function SimplePage({ title, detail }: { title: string; detail: string }) { return <><Header title={title} detail={detail} /><Paper sx={{ ...surface, p: 5 }}><EmptyState label={title === 'Integrations' ? 'GitHub not connected' : 'No settings configured'} /></Paper></>; }

export function AdminDashboard() {
  const [mobileOpen, setMobileOpen] = useState(false); const [revision, setRevision] = useState(0); const location = useLocation(); const path = location.pathname; const bump = () => setRevision((value) => value + 1);
  let page: ReactNode = <DashboardPage revision={revision} />;
  if (path.endsWith('/users')) page = <UsersPage onChange={bump} />; else if (path.endsWith('/projects')) page = <ProjectsPage onChange={bump} />; else if (path.endsWith('/integrations')) page = <SimplePage title="Integrations" detail="Connect GitHub through a backend OAuth flow before repositories can appear here." />; else if (path.endsWith('/ai-settings')) page = <AISettingsPage />; else if (path.endsWith('/activity')) page = <ActivityPage />; else if (path.endsWith('/settings')) page = <SimplePage title="Settings" detail="Workspace and security settings are ready for backend persistence." />;
  return <Box sx={{ minHeight: '100vh', bgcolor: '#f7f9fc' }}><AdminSidebar open={mobileOpen} onClose={() => setMobileOpen(false)} /><Box sx={{ ml: { xs: 0, md: '268px' } }}><Toolbar sx={{ display: { xs: 'flex', md: 'none' }, bgcolor: '#fff', borderBottom: '1px solid #e5eaef' }}><IconButton onClick={() => setMobileOpen(true)} aria-label="Open admin navigation"><Menu /></IconButton><Typography sx={{ ml: 1, color: ink, fontWeight: 800 }}>Admin Console</Typography></Toolbar><Box component="main" sx={{ maxWidth: 1600, mx: 'auto', px: { xs: 2, sm: 3.5, lg: 5 }, py: { xs: 3, md: 5 } }}>{page}</Box></Box></Box>;
}
